### ISSUE TITLE
Protect 'master' branch on our GitHub repository

### ISSUE THREAD

**Issue by FaaPz** [xebia-research/header-checker-REST#2]

**Comment by commjoen** [comment]
Master is now protected and needs a PR with a green build in travis-CI

**Comment by FaaPz** [comment]
Thanks @commjoen! Our `master` branch is indeed protected against (force-)pushing:

![Our 'master' branch is protected!](https://user-images.githubusercontent.com/1536742/30481196-a4be6ab4-9a1d-11e7-99de-e46c39aa7657.png)
