### ISSUE TITLE
Grant access to staging server

### ISSUE THREAD

**Issue by FaaPz** [xebia-research/header-checker-REST#45]

**Comment by remondoo-sne** [comment]
Issues with network adapter, fix applied. 

Done:
- Generated an account for each team member.
- Generated a public and private key for server access.

To-do:
Configuring VLAN for API-server
Share private key with team members, open ssh port.

**Comment by FaaPz** [comment]
Staging/acceptance server is already accessible via SSH, configured by @remondoo-sne.
