### ISSUE TITLE
Set up temporary local development environment for every team member

### ISSUE THREAD

**Issue by FaaPz** [xebia-research/header-checker-REST#50]
Until our Docker image (see #51) is ready, we will use the following stack:

- [PhpStorm](https://www.jetbrains.com/phpstorm/)
- [SourceTree](https://www.sourcetreeapp.com/) or [GitKraken](https://www.gitkraken.com/) (for non-terminal users)
- [MAMP](https://www.mamp.info/en/) or [XAMPP](https://www.apachefriends.org/)
- [Composer](https://getcomposer.org/)

Please comment `I'm ready!` once everything is installed.

**Comment by FaaPz** [comment]
I'm ready! :metal:

**Comment by sjongejan** [comment]
```I'm ready!```

**Comment by CasperMons** [comment]
Done

**Comment by remondoo-sne** [comment]
Ready!

**Comment by carlo1234567890** [comment]
Ready
