### ISSUE TITLE
[SPIKE] Find best practices, why are these best practices and why do they work(why are they regarded as best practices)

### ISSUE THREAD

**Issue by carlo1234567890** [xebia-research/header-checker-REST#66]

**Comment by carlo1234567890** [comment]
Best practices have been found, not yet why they are necessary best practices.

Not yet documented

**Comment by carlo1234567890** [comment]
Finding so far
[Find best practices.pdf](https://github.com/xebia-research/header-checker-REST/files/1355880/Find.best.practices.pdf)

**Comment by FaaPz** [comment]
Looking good @carlo1234567890! I would like to see the sources where to find this information (hyperlinks are 👌 ) in the document(s) itself.

Furthermore, aren't some X-headers also best practices? If so, I would like to see them also in this document. 😄

**Comment by carlo1234567890** [comment]
I applied the feedback from the group and updated the document
[Find best practices 18-10-2017.pdf](https://github.com/xebia-research/header-checker-REST/files/1394168/Find.best.practices.18-10-2017.pdf)
