### ISSUE TITLE
[SPIKE] Find out how old servers/header are build and why this is not safe

### ISSUE THREAD

**Issue by carlo1234567890** [xebia-research/header-checker-REST#67]

**Comment by carlo1234567890** [comment]
There have not yet been any, good, information found

**Comment by carlo1234567890** [comment]
Progress so far
[Find out how old servers(headers) are formatted.pdf](https://github.com/xebia-research/header-checker-REST/files/1362763/Find.out.how.old.servers.headers.are.formatted.pdf)

**Comment by FaaPz** [comment]
Great start! I would really like to see a list of headers (or header orders) for MS ISS, Apache and Nginx which can be used to _actually_ recognize those versions per web server.

Also, sources please! 😉

**Comment by carlo1234567890** [comment]
I applied the feedback from the group and updated the document.
Also the feedback with regards to see a list of headers for IIS:
It is stated under "Appears as"

For apache the details SHOULD be stored in mod_header, however so far I haven't found the correct information, so it is still work in progress
[Find out how old servers(headers) are formatted 18-10-2017.pdf](https://github.com/xebia-research/header-checker-REST/files/1394302/Find.out.how.old.servers.headers.are.formatted.18-10-2017.pdf)

**Comment by carlo1234567890** [comment]
Made some changes to the file. Namely the fact that the research hasn't given any indication that the format of Apache versions show what version of Apache is running, other than the fact that in the standard configuration it says it which version it runs.
[Find out how old servers(headers) are formatted 18-10-2017.pdf](https://github.com/xebia-research/header-checker-REST/files/1394479/Find.out.how.old.servers.headers.are.formatted.18-10-2017.pdf)

**Comment by carlo1234567890** [comment]
Updated the file so that in now also includes Nginx
[Find out how old servers(headers) are formatted 20-10-2017.pdf](https://github.com/xebia-research/header-checker-REST/files/1401802/Find.out.how.old.servers.headers.are.formatted.20-10-2017.pdf)
