### ISSUE TITLE
[SPIKE] Find out which headers are good headers to have with regards to X- headers

### ISSUE THREAD

**Issue by carlo1234567890** [xebia-research/header-checker-REST#68]

**Comment by carlo1234567890** [comment]
All the necessary information has been found, but the findings haven't been documented as of yet

**Comment by carlo1234567890** [comment]
Progress so far is written in the PDF
[Good headers to have with regards to safety 29-09-2017.pdf](https://github.com/xebia-research/header-checker-REST/files/1344467/Good.headers.to.have.with.regards.to.safety.29-09-2017.pdf)

**Comment by FaaPz** [comment]
Very well-written with great examples!

Do add the sources (hyperlinks) though. 😄

**Comment by carlo1234567890** [comment]
I applied the feedback from the group and updated the document
[Good headers to have with regards to safety 18-10-2017.pdf](https://github.com/xebia-research/header-checker-REST/files/1394213/Good.headers.to.have.with.regards.to.safety.18-10-2017.pdf)

**Comment by carlo1234567890** [comment]
-There are a couple of CSP header versions, 
-We need to find more information with regards to hPKP

**Comment by carlo1234567890** [comment]
Updated and closing
